server:
  port: 8080

spring:
  config:
    import: classpath:secret.yml

  activate:
    on-profile: dev

  application:
    name: ONLOG-AUTH-SERVER

  jpa:
    hibernate:
      ddl-auto: none

    database-platform: org.hibernate.dialect.MySQL8Dialect

    properties:
      hibernate:
        format_sql: true

    show-sql: true

springdoc:
  show-login-endpoint: true

eureka:
  instance:
    appname: ONLOG-AUTH-SERVER
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://172.16.213.26:8761/eureka
